# Generated by Django 5.2.5 on 2025-08-08 08:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('survey_type', models.CharField(choices=[('household', 'Household Survey'), ('enterprise', 'Enterprise Survey'), ('agriculture', 'Agriculture Survey'), ('consumption', 'Consumption Expenditure Survey'), ('employment', 'Employment Survey'), ('other', 'Other')], default='other', max_length=20)),
                ('original_file', models.FileField(upload_to='surveys/original/')),
                ('file_type', models.CharField(max_length=10)),
                ('file_size', models.PositiveIntegerField()),
                ('total_rows', models.PositiveIntegerField(blank=True, null=True)),
                ('total_columns', models.PositiveIntegerField(blank=True, null=True)),
                ('has_weights', models.BooleanField(default=False)),
                ('weight_column', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surveys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProcessingJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('configuration', models.JSONField(default=dict)),
                ('progress_percentage', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('processed_file', models.FileField(blank=True, upload_to='surveys/processed/')),
                ('results_summary', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processing_jobs', to=settings.AUTH_USER_MODEL)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processing_jobs', to='api.survey')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.CharField(blank=True, max_length=255)),
                ('organization_type', models.CharField(blank=True, choices=[('government', 'Government Agency'), ('academic', 'Academic Institution'), ('ngo', 'Non-Government Organization'), ('private', 'Private Organization'), ('individual', 'Individual Researcher')], max_length=20)),
                ('department', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('bio', models.TextField(blank=True)),
                ('preferred_language', models.CharField(default='en', max_length=10)),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('notification_preferences', models.JSONField(default=dict)),
                ('api_access_level', models.CharField(choices=[('basic', 'Basic'), ('advanced', 'Advanced'), ('admin', 'Administrator')], default='basic', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProcessingStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('step_type', models.CharField(choices=[('upload', 'File Upload'), ('validation', 'Data Validation'), ('cleaning', 'Data Cleaning'), ('imputation', 'Missing Value Imputation'), ('outlier_detection', 'Outlier Detection'), ('rule_validation', 'Rule-based Validation'), ('weight_application', 'Weight Application'), ('estimation', 'Statistical Estimation'), ('report_generation', 'Report Generation')], default='validation', max_length=30)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=20)),
                ('order', models.PositiveIntegerField()),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('results', models.JSONField(default=dict)),
                ('logs', models.TextField(blank=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='api.processingjob')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('job', 'order')},
            },
        ),
        migrations.CreateModel(
            name='SurveyColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('original_name', models.CharField(max_length=255)),
                ('data_type', models.CharField(choices=[('numeric', 'Numeric'), ('categorical', 'Categorical'), ('text', 'Text'), ('date', 'Date'), ('boolean', 'Boolean')], max_length=20)),
                ('is_required', models.BooleanField(default=False)),
                ('is_weight', models.BooleanField(default=False)),
                ('missing_count', models.PositiveIntegerField(default=0)),
                ('unique_count', models.PositiveIntegerField(default=0)),
                ('min_value', models.FloatField(blank=True, null=True)),
                ('max_value', models.FloatField(blank=True, null=True)),
                ('mean_value', models.FloatField(blank=True, null=True)),
                ('std_value', models.FloatField(blank=True, null=True)),
                ('position', models.PositiveIntegerField()),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='api.survey')),
            ],
            options={
                'ordering': ['position'],
                'unique_together': {('survey', 'position')},
            },
        ),
    ]
